# Generated by Django 2.0.9 on 2018-12-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('total_unit_number', models.CharField(max_length=255, null=True)),
                ('used_unit_number', models.CharField(max_length=255, null=True)),
                ('available_unit_number', models.CharField(max_length=255, null=True)),
                ('cabinet_row', models.CharField(max_length=50)),
                ('cabinet_col', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='computer_room.Cabinet')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_unit_department', to='users.Department')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='equipment.Machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='computer_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_room', to='computer_room.ComputerRoom'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='plan_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_department', to='users.Department'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='used_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_department', to='users.Department'),
        ),
    ]
