# Generated by Django 2.0.9 on 2018-12-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinetunit',
            old_name='status',
            new_name='state',
        ),
    ]
