# Generated by Django 2.0.9 on 2018-12-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer_room', '0002_auto_20181227_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cabinetunit',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_unit_department', to='users.Department'),
        ),
        migrations.AlterField(
            model_name='cabinetunit',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cabinetunit',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='equipment.Machine'),
        ),
        migrations.AlterField(
            model_name='computerroom',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
