# Generated by Django 2.0.9 on 2019-01-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190103_1726'),
        ('computer_room', '0004_auto_20190103_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetunit',
            name='department',
        ),
        migrations.AddField(
            model_name='cabinetunit',
            name='plan_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_unit_plan_department', to='users.Department'),
        ),
        migrations.AddField(
            model_name='cabinetunit',
            name='used_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_unit_used_department', to='users.Department'),
        ),
    ]
