# Generated by Django 2.0.9 on 2019-01-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer_room', '0006_auto_20190114_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetunit',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_units', to='equipment.Machine'),
        ),
    ]
