# Generated by Django 2.0.9 on 2018-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('equip_model', models.CharField(max_length=50)),
                ('equip_type', models.CharField(max_length=50)),
                ('equip_sn', models.CharField(max_length=255)),
                ('equip_use', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
