# Generated by Django 2.0.9 on 2018-12-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_department', to='users.Department'),
        ),
        migrations.AddField(
            model_name='machine',
            name='u_count',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equip_model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equip_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equip_use',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
