# Generated by Django 2.0.9 on 2019-01-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20181227_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='equip_model',
            new_name='equip_version',
        ),
    ]
