# Generated by Django 2.0.9 on 2018-12-26 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('char_value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_key', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '自定义工单字段',
                'verbose_name_plural': '自定义工单字段',
            },
        ),
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(max_length=25, verbose_name='SN')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='Title')),
                ('participant_type', models.CharField(choices=[('1', 'person'), ('2', 'department')], default='1', max_length=5, verbose_name='Participant Type')),
                ('is_end', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_record_creator', to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_record_state', to='workflow.State')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_record_participant', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ManyToManyField(related_name='ticket_record_related_user', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_record_workflow', to='workflow.Workflow')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
        migrations.AddField(
            model_name='ticketcustomfield',
            name='ticket_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketRecord'),
        ),
    ]
