# Generated by Django 2.0.9 on 2019-01-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcustomfield',
            name='original_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
