# Generated by Django 2.0.9 on 2019-01-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketcustomfield_original_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='original_value',
        ),
    ]
